# Generated by Django 5.2.9 on 2025-12-12 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('systolic', models.IntegerField(help_text='Systolic pressure (upper number)')),
                ('diastolic', models.IntegerField(help_text='Diastolic pressure (lower number)')),
            ],
            options={
                'verbose_name': 'Blood Pressure',
                'verbose_name_plural': 'Blood Pressures',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['person_id', 'date'], name='motion_bloo_person__ac439f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=1)),
                ('date_time', models.DateTimeField()),
                ('date', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('height', models.DecimalField(decimal_places=1, help_text='Height in cm', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=1, help_text='Weight in kg', max_digits=5)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, help_text='Body fat percentage', max_digits=5, null=True)),
                ('bone', models.DecimalField(blank=True, decimal_places=1, help_text='Bone mass in kg', max_digits=5, null=True)),
                ('muscle', models.DecimalField(blank=True, decimal_places=1, help_text='Muscle mass in kg', max_digits=5, null=True)),
                ('vfat', models.DecimalField(blank=True, decimal_places=1, help_text='Visceral fat', max_digits=5, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=1, help_text='Body moisture percentage', max_digits=5, null=True)),
                ('calorie', models.IntegerField(blank=True, help_text='Daily calorie intake', null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, help_text='Body Mass Index', max_digits=5, null=True)),
                ('muscle_p', models.DecimalField(blank=True, decimal_places=1, help_text='Muscle percentage', max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['person_id', 'date'], name='motion_weig_person__96ab7d_idx')],
            },
        ),
    ]
