# Generated by Django 5.2.9 on 2026-01-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('no_pictures', models.IntegerField(blank=True)),
            ],
        ),
    ]
