# Generated by Django 5.2.9 on 2026-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('no_pictures', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
