# Generated by Django 5.2.9 on 2026-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_album_delete_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='no_video',
            field=models.IntegerField(default=0),
        ),
    ]
