# Generated by Django 5.2.9 on 2026-02-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_album_no_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='place',
            field=models.CharField(default='', max_length=40),
        ),
    ]
